### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by kentcdodds** [remark-embedder/core#1]
We need to add `remark-embedder-bot` to the `remark-embedder` org on npm. Once that's done, then we just need to kick off the most recent [action](https://github.com/remark-embedder/core/actions) and it should auto-release without trouble (I've already set the npm token).

**Comment by kentcdodds** [comment]
I updated the `NPM_TOKEN` to my own for the time being. @MichaelDeBoey, once you add `remark-embedder-bot` to the `remark-embedder` org on npm, let me know and I'll switch it back to a bot token 👍

**Comment by MichaelDeBoey** [comment]
Added 🙂

**Comment by kentcdodds** [comment]
Sweet! I've updated the `NPM_TOKEN`. Thanks 👏
